# Generated by Django 4.1.6 on 2023-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('ct_scan', models.ImageField(upload_to='ct_scans/')),
                ('result', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
